#!/bin/sh

case "$1" in
    start)
        cd /lib/modules/5.15.148-yocto-standard/extra

        module="faulty"
        device="faulty"
        mode="664"

        # Group: since distributions do it differently, look for wheel or use staff
        if grep -q '^staff:' /etc/group; then
            group="staff"
        else
            group="wheel"
        fi

        set -e
        echo "Load our module, exit on failure"
        insmod ./$module.ko || exit 1
        echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
        major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
        if [ ! -z ${major} ]; then
            echo "Remove any existing /dev node for /dev/${device}"
            rm -f /dev/${device}
            echo "Add a node for our device at /dev/${device} using mknod"
            mknod /dev/${device} c $major 0
            echo "Change group owner to ${group}"
            chgrp $group /dev/${device}
            echo "Change access mode to ${mode}"
            chmod $mode  /dev/${device}
        else
            echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
        fi
        
        modprobe hello
        ;;
    stop)
        module="faulty"
        device="faulty"
        # invoke rmmod with all arguments we got
        rmmod $module || exit 1

        # Remove stale nodes
        rm -f /dev/${device}

        module="hello"
        device="hello"

        # invoke rmmod with all arguments we got
        rmmod $module || exit 1

        # Remove stale nodes
        rm -f /dev/${device}
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0
